name: Release

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled, closed]

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pull-requests: read
    uses: Nucleo-Estudantes-Informatica-ISEP/.github/.github/workflows/release.yml@master
    with:
      product_name: Fallstack
