name: Security

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:

jobs:
  security:
    name: Security
    permissions:
      contents: read
    uses: Nucleo-Estudantes-Informatica-ISEP/.github/.github/workflows/security.yml@master
